### ISSUE TITLE
Error when add new scheduler task

### ISSUE THREAD

**Issue by leckelmann** [Apen/additional_scheduler#13]
I get this error message when I try to add the scheduler task "Backup a website".
My config is...
TYPO3 10.4.10
PHP 7.3.25
Scheduler 10.4.10
In a Docker envirenmoent
```
Oops, an error occurred!
Call to protected method TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage() from context 'Sng\Additionalscheduler\BaseAdditionalFieldProvider'
```

**Comment by apgl64** [comment]
Hello,
I have the same problem. Have you solve it ?

**Comment by Apen** [comment]
Try the last version 1.5.4, should be fine
