### ISSUE TITLE
Info about error

### ISSUE THREAD

**Issue by j-nicolas** [Apen/additional_scheduler#15]
Hi there!

I use Typo3 Version 9.5.4,
ISP: Operating system: | Unix
PHP version: | 7.2.34-nmm1
PHP CGI detected: | No
scheduler | 9.5.4
additional_scheduler | 1.5.4

The "Scheduler test task" works fine and I get an email.
But a Backup-Task results to a red error-bar without further information.
No entries in the system log.

How can I find out?
Thanks in advance - Nicolas

**Comment by Apen** [comment]
Maybe a permission problem?
Did you have something in the server system log?

**Comment by Apen** [comment]
Try to execute the save script directly in command line to see what happen

**Comment by Apen** [comment]
Are always blocked on this?

**Comment by Apen** [comment]
Like i said before, do you have permission in this directory whith your apache user? 90% of the time its a permission problem.

**Comment by Apen** [comment]
Maybe a timeout issue? is it after a long time?
I suppose you didnt receive any emails?
Did you check your system log?

**Comment by Apen** [comment]
Ok strange, did you have a particular setup : docker, composer...
Does apache have access to the mysql, mysqdump... executables?
Try the "exec SH task" with /typo3conf/ext/additional_scheduler/Resources/Shell/test.sh to check is a basic script is executable

**Comment by NasimoOo** [comment]
my problem was that the file  `/typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh` was not executable. Changing the permissions of the file to 755 fixed the issue. 

An error message like "Please check you file permissions" would have helped.

**Comment by Apen** [comment]
it is the case, on task saving, we have an Exception with the path  and "must be executable".
Nice that it works for you :-)
