### ISSUE TITLE
Variable for backup path

### ISSUE THREAD

**Issue by schrej-zz** [Apen/additional_scheduler#18]
Hi,
are you able to implement the usage of a variable in the backup path, so that the directory of the backup can be made dependent eg. from production state.

Example: I have 3 Typo3 versions of Typo3 running (DEV/Test/Production).
Im copying the files and DBs from one version to the other from time to time.
As the backup path of the extension is in the database, the backups of the 3 versions are overwriting each other.
This can be prevented by the usage of a variable in the path.
Or is this already possible in some way?

**Comment by schrej-zz** [comment]
Forget the issue.
As the DB name is partb of the backup, no overwriting should happen.

**Comment by Apen** [comment]
ok :)
