### ISSUE TITLE
Backup fails as of mysqldump access rights

### ISSUE THREAD

**Issue by schrej-zz** [Apen/additional_scheduler#19]
At least I get an error when trying to backup.
The eMail notes the following error:
`mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`

Adding the parameter `--no-tablespaces` to the command in the shell script solved the issue.

**Comment by Apen** [comment]
Solve in last PR
