### ISSUE TITLE
MailUtility::getSystemFrom() returns null || indexed array || assoc array

### ISSUE THREAD

**Issue by nalmar** [Apen/additional_scheduler#23]
Hi,

I had a problem with the "Execute a schell script" task, when sendEmail() function of Utils.php gets :
```        $from = MailUtility::getSystemFrom(); ```
it can get null if $GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromAddress'] is not set or $from[0] can be null if $GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromName'] is set. In both cases, the task fail with an exception.

It can be fixed with this as the begining of the sendmail function :
```         $from = MailUtility::getSystemFrom();

        if ( $from === null ) throw new \RuntimeException( 'System email is not configured', 165282396 );
        $fromAdress = key($from);
        if ( is_numeric($fromAdress) ) $fromAdress = $from[0];

        $mail = GeneralUtility::makeInstance(MailMessage::class);
        if (version_compare(TYPO3_version, '10.4.0', '>=')) {
            $mail
                ->from(new Address($fromAdress))
```

**Comment by Apen** [comment]
Fix in last version, thanks for your feedback.

**Comment by nalmar** [comment]
Thanks ! Will there be a 1.5.7 release with this correction ?

**Comment by Apen** [comment]
It will be 1.5.8 that is released now, because of my old github action release...
