### ISSUE TITLE
BaseAdditionalFieldProvider::initFields() is called with null argument by sysext/scheduler when adding a new task

### ISSUE THREAD

**Issue by nalmar** [Apen/additional_scheduler#24]
Adding a new task ( it works when modifying an existing one ) :
```Argument 2 passed to Sng\Additionalscheduler\BaseAdditionalFieldProvider::initFields() must be an instance of TYPO3\CMS\Scheduler\Task\AbstractTask, null given, called in /var/www/public/typo3conf/ext/additional_scheduler/Classes/BaseAdditionalFieldProvider.php on line 105```

since 1.5.7 :
```protected function initFields(array &$taskInfo, AbstractTask $task, SchedulerModuleController $parentObject): void```
instead of the pre 1.5.7 :
```protected function initFields(array &$taskInfo, $task, SchedulerModuleController $parentObject): void```

i'm on typo3 10.4.32, typo3 scheduler call additional_scheduler on ligne 604 of SchedulerModuleController.php :
```$additionalFields = $providerObject->getAdditionalFields($taskInfo, null, $this);```

**Comment by Apen** [comment]
Should be fixed in last release 1.5.9
