### ISSUE TITLE
BOM + date in CSV file name

### ISSUE THREAD

**Issue by nalmar** [Apen/additional_scheduler#25]
Me again :)

Could you add a UTF-8 BOM mark to the CSV file to please the buggy but unfortunately unavoidable MS Excel :
CsvExportManager.php : 85
```
$handle = fopen($temp, 'w');
fputs($handle, $bom =( chr(0xEF) . chr(0xBB) . chr(0xBF) ));
```

also, the checkbox field of the BE task creation interface don't work : noHeader and noDatetimeFlag both revert to unchecked on save and don't apply to the resulting email. I think it has to do with data types, noDatetimeFlag";s:0:"" in the db, interpreted as an int in the code and tested with noDatetimeFlag === 0

additional_scheduler 1.5.9
Typo3 10.4.32 if it matters.

Thanks again for your time

**Comment by Apen** [comment]
Thanks a lot for you PR, its merged 👍
