### ISSUE TITLE
Cannot create task

### ISSUE THREAD

**Issue by simtecsoft** [Apen/additional_scheduler#27]
Hello! I have version 1.5.9 installed and I wanted to create the Back up a website task. But no matter what I try, I get an empty error message:

<img width="1427" alt="Bildschirmfoto 2023-05-17 um 11 59 28" src="https://github.com/Apen/additional_scheduler/assets/36533375/717d0f9d-660e-403e-9f00-dc74570a8f76">

Following error appears in the log:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: strftime() expects parameter 2 to be int, string given | TypeError thrown in file /home/.sites/53/site5845083/web/typo3_src-11.5.16/typo3/sysext/scheduler/Classes/Controller/SchedulerModuleController.php in line 701. Requested URL: http://www.lilawinkel.at/typo3/module/system/txschedulerM1?token=--AnonymizedToken--&CMD=add`

I found it only once, so it might be due to other tries of me.

Do you know what is happening?

Thanks in advance!

**Comment by simtecsoft** [comment]
Has anyone else this problem? I have removed and installed it several times, the problem is the same! Please help!

**Comment by Apen** [comment]
Seems to be not relative to additional_scheduler but to typo3.
Youre line link to 

`
 // @todo Replace deprecated strftime in php 8.1. Suppress warning in v11.
$this->view->assign('end_value_hr', ($taskInfo['end'] > 0 ? @strftime($dateFormat, $taskInfo['end']) : ''));
`

it seems to be a bug with php 8.1 and scheduler but only relative to "end" date. Try delete this date wich appear to be unecessary.
