### ISSUE TITLE
 Test Mail Setup

### ISSUE THREAD

**Issue by criwe** [Apen/additional_scheduler#29]
Hi,

what about an scheduler task to test the mail setup on regulary base? 

In rare cases the given data didn´t work anymore, i. e. changes on the hosters side. So it would be great to get information, if that happens, because not working forms are a big problem. 

Problem: how to inform the admin, if mailing is defect?! Maybe browser notification at the next login or entry in the be-syslog?

Best regards,
Chris

**Comment by Apen** [comment]
I dont think its a "scheduler" thing.
The "reports" module is dedicated to check things, it must be add here. And in install tool we have a check mail module.

**Comment by criwe** [comment]
Ok, thanks for your feedback!
