### ISSUE TITLE
CSV instead of html tables in SQL email export

### ISSUE THREAD

**Issue by gaumondp** [Apen/additional_scheduler#5]
Adding an option to export data as CSV file attachments in emails would be great.

Very handy extension !

**Comment by Apen** [comment]
Maybe it can be a feature, but i dont have many time to maintain this extension for the moment.

**Comment by Apen** [comment]
Is it still usefull for you?

**Comment by gaumondp** [comment]
The general feature (SQL into email body) of your extension is used in about 15 different daily cronjob here. So we're grateful to you for providing it!

So far our editors have lived with the copy-paste of the content in email to Excel but I'm pretty sure CSV would still be preferred...

**Comment by Apen** [comment]
I have updated my version to work with 9 LTS, i can add this feature, but it will be only compatible with the last LTS version.

**Comment by gaumondp** [comment]
We're probably on 8.7 LTS for another year and wait to go directly with 10 LTS...

**Comment by Apen** [comment]
I think it will works for 8 LTS to 10 LTS. Stay tuned

**Comment by Apen** [comment]
Must be good in last git version thanks to @marc-munos 👍
