### ISSUE TITLE
Not working: Backup gives "export_" file

### ISSUE THREAD

**Issue by jkkoenig** [Apen/additional_scheduler#6]
I cannot do a backup with your extension. In the backup folder a "export_" file is generated. This is the log-email:
```
/home/strato/http/premium/..../typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh -p /home/strato/http/premium/.../ -o /home/strato/http/premium/.../backup/ -f

Thu Jul 26 09:03:18  2018
Checking dependencies...Succeeded.
-----------------------------------------------------------------------
Informations
-----------------------------------------------------------------------
Date               : 20180726
Website size       : 823M	
Size of the DB     : 0M
TYPO3 version      : 8.7.17
PATH_site          : /home/strato/http/premium/...
Tar file           : /home/strato/http/premium/.../backup/export_                'dbname' => 'DB299xxxx',-20180726.tar.gz
SQL file           : export_                'dbname' => 'DB299xxxx',-20180726.sql
-----------------------------------------------------------------------
Check informations in 'typo3conf/LocalConfiguration.php'
-----------------------------------------------------------------------
typo_db_host       :                 'host' => 'rdbms.strato.de',
typo_db_username   :                 'user' => 'U299xxxx',
typo_db            :                 'dbname' => 'DB299xxxx',

-----------------------------------------------------------------------
Dump the DB                 'dbname' => 'DB299xxxx',...
-----------------------------------------------------------------------
/home/strato/http/premium/.../typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh: line 264: $filenamesql: ambiguous redirect
/home/strato/http/premium/.../typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh: line 265: $filenamesql: ambiguous redirect
-----------------------------------------------------------------------
Compress the files and DB...
-----------------------------------------------------------------------
tar: 'dbname': Cannot stat: No such file or directory
tar: =>: Cannot stat: No such file or directory
tar: 'DB299xxxx',-20180726.tar.gz: Cannot stat: No such file or directory
```

Thank you for your help!

**Comment by jkkoenig** [comment]
Hello, is anybody reading this?

**Comment by Apen** [comment]
Yes, im here :-)

The script "/typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh" apparentrly doesnt work you. It seems that he cannot get the database infos. Is there any comments or strange formating in your "LocalConfiguration.php"?

**Comment by jkkoenig** [comment]
thank you for your answer. Localconfigurations.php seems to be ok. I made a test with the data for DB Connection. DB User, password, host and database are ok. this is localconfiguration.php:
 `<?php
return [
    'BE' => [
        'compressionLevel' => '5',
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => 'xxxx',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => 'DB299xxxx',
                'driver' => 'mysqli',
                'host' => 'rdbms.strato.de',
                'password' => 'xxxx',
                'port' => 3306,
                'user' => 'U299xxxx',
            ],
        ],
    ],
    'EXT' => [
        'extConf' => [
            'about' => 'a:0:{}',
            'additional_scheduler' => 'a:0:{}',
            'backend' => 'a:5:{s:9:"loginLogo";s:32:"fileadmin/templates/img/Logo.png";s:19:"loginHighlightColor";s:0:"";s:20:"loginBackgroundImage";s:58:"fileadmin/templates/img/hintergrund-startseite1360tiny.png";s:11:"backendLogo";s:37:"fileadmin/templates/img/Logo_22px.png";s:14:"backendFavicon";s:0:"";}',
            'belog' => 'a:0:{}',
            'beuser' => 'a:0:{}',
            'bootstrap_package' => 'a:9:{s:21:"disableLessProcessing";s:1:"0";s:36:"disablePageTsNewContentElementWizard";s:1:"0";s:30:"disablePageTsTtContentPreviews";s:1:"0";s:16:"disablePageTsRTE";s:1:"0";s:20:"disablePageTsTCEFORM";s:1:"0";s:20:"disablePageTsTCEMAIN";s:1:"0";s:21:"disablePageTsAdmPanel";s:1:"0";s:27:"disablePageTsBackendLayouts";s:1:"0";s:4:"Logo";s:84:"../typo3conf/ext/bootstrap_package/Resources/Public/Images/Backend/TopBarLogo@2x.png";}',
            'cb_foundation' => 'a:2:{s:6:"useRTE";s:1:"1";s:9:"addPanels";s:1:"1";}',
            'compatibility7' => 'a:0:{}',
            'context_help' => 'a:0:{}',
            'cshmanual' => 'a:0:{}',
            'css_styled_content' => 'a:1:{s:32:"loadContentElementWizardTsConfig";s:1:"1";}',
            'documentation' => 'a:0:{}',
            'facebookpage' => 'a:0:{}',
            'felogin' => 'a:0:{}',
            'fluid_styled_content' => 'a:1:{s:32:"loadContentElementWizardTsConfig";s:1:"1";}',
            'form' => 'a:0:{}',
            'func' => 'a:0:{}',
            'impexp' => 'a:0:{}',
            'info' => 'a:0:{}',
            'info_pagetsconfig' => 'a:0:{}',
            'lowlevel' => 'a:0:{}',
            'ns_all_lightbox' => 'a:0:{}',
            'realurl' => 'a:6:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";}',
            'reports' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rte_ckeditor' => 'a:0:{}',
            'rtehtmlarea' => 'a:8:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'sd_lightbox' => 'a:0:{}',
            'setup' => 'a:0:{}',
            'sys_note' => 'a:0:{}',
            't3editor' => 'a:0:{}',
            'tstemplate' => 'a:0:{}',
            'viewpage' => 'a:0:{}',
            'wizard_crpages' => 'a:0:{}',
            'wizard_sortpages' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'FE' => [
        'compressionLevel' => '5',
        'debug' => false,
        'loginSecurityLevel' => 'rsa',
    ],
    'GFX' => [
        'jpg_quality' => '80',
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'RGB',
        'processor_effects' => -1,
        'processor_enabled' => 1,
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'INSTALL' => [],
    'MAIL' => [
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i ',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'devIPmask' => '',
        'displayErrors' => 0,
        'enableDeprecationLog' => false,
        'encryptionKey' => '2cb2e5aeada72fe803df7f0ffc04c6393b6153566245c04fc669349a8f118faaacbd6d1ba44501c23d711c1e3e04a9ac',
        'exceptionalErrors' => 20480,
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'sitename' => 'xxxx',
        'sqlDebug' => 0,
        'systemLogLevel' => 2,
    ],
];
`
Any other ideas? In November 2017 Your plugin did work.

**Comment by Apen** [comment]
If you try to launch /typo3conf/ext/additional_scheduler/Resources/Shell/save_typo3_website.sh (without validating the dump) what did you have?

**Comment by jkkoenig** [comment]
Now I get an internal server error in Typo3 when executing the additional-scheduler backup in the scheduler. I will get an export_ file with about 50MB

I set save_typo3_website.sh user permissions to 774, as well to /typo3/sysext/core/bin/typo3 scheduler. both were not executable after installation due to failing user permission

**Comment by jkkoenig** [comment]
next try: start the scheduler from a php script as described here: https://blog.mobasoft.de/typo3/typo3-scheduler-cronjob-bei-strato/

`<?php
exec('pwd', $myResult);
$myPath = $myResult[0];
system ('env -i /bin/php71 -f ' . $myPath . '/typo3/sysext/core/bin/typo3 scheduler:run');
?>`

This also give an Internal Server Error.

Unfortunately I only have access to FTP and not SSH or the hosting company.

Is there any other solution to get a backup of the database from within Typo3?

**Comment by jkkoenig** [comment]
I wrote a php-script to manually backup the database:
https://www.php-einfach.de/experte/php-sicherheit/daten-sicher-speichern/datenbankbackup-per-php/

It is so sad, that there are so many extensions not working in Typo3...

**Comment by Apen** [comment]
It works well for a lot of people, using it in all my typo3 installations. It seems a permission problem.

**Comment by kledo-34** [comment]
I confirm to get the exact same error, I'm also on the hosting company strato, if anyone will get a solution for this in the future, feel free to post it here ;)

**Comment by kledo-34** [comment]
Further Question here:
I found out that strato webhost runs with PHP_APIS = cgi also on command line and cron jobs instead of cli, maybe that causes some issues (not sure if that's the problem, I don't understand much of the server configuration logic and variables, but this made problems for other scheduler tasks aswell, e.g. the STDIN variable is only available if cli is used.
However:
I can simply replace the dbname, user, host and password in the script manually to make the database connection work, but then I get a message
gzip: stdout: File too large
The 
Website size       : 54G	.
Size of the DB     : 29.9551M

seems to be crazy to me, does this mean the website should habe 54GB, this is not the case, what is going on here?
Maybe someone understands things in here ;)

**Comment by RobertKesseler** [comment]
Abandon all hope, ye who use Strato... Strato Servers have a lot of problems and Strato just does not care
