### ISSUE TITLE
typo3 9 Update?

### ISSUE THREAD

**Issue by X-Tender** [Apen/additional_scheduler#7]
is it possible to make it typo3 9  compatible?

**Comment by Apen** [comment]
hi, i need to work on it, im a little late on 9 compatibility but its definitively scheduled :-)

**Comment by Epoche-Napoleon** [comment]
That's nice to hear.

**Comment by EnzephaloN** [comment]
Hello
I'm also interested in an TYPO3 9.5.x-compatible version.

Thanx in advance
EnzephaloN

**Comment by Apen** [comment]
Lot of bugfixes, must be good now on 9 LTS.

**Comment by EnzephaloN** [comment]
Thanx a lot. Installed without errors, jobs are running without errors.
Good work!

**Comment by Apen** [comment]
Glad to hear that :-)
