### ISSUE TITLE
Support of PHP 7.3.x

### ISSUE THREAD

**Issue by bh-teufels** [Apen/additional_scheduler#8]
is there a plan if / when PHP 7.3.x (7.3.5) will be supported?
Thank you

**Comment by schrej-zz** [comment]
Hi,
now, we are already at PHP 7.4.
_"HP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in ....
ext/additional_scheduler/Classes/Tasks/class.tx_additionalscheduler_exec_fields.php line 58"_
Braces {} have to be replaced by brackets []

**Comment by Apen** [comment]
Yes definitively want to do a compat version, its in the pipe

**Comment by Apen** [comment]
Must be good (7.3 & 7.4) with the last commit patch if you want to test.
Final version will be 10 LTS compat.
